Vastly improve error handling

diff --git a/pomfclip b/pomfclip
--- a/pomfclip
+++ b/pomfclip
@@ -4,16 +4,19 @@ lock="/tmp/pomfclip-$DISPLAY"
 exec 4>"$lock"
 if flock -n 4; then
     file=""
+    errorfile=""
     cleanup() {
         code=$?
-        [ -n "$file" ] && rm "$file"
-        rm "$lock"
+        [ -n "$file" ] && rm -f -- "$file"
+        [ -n "$errorfile" ] && rm -f -- "$errorfile"
+        rm -f -- "$lock"
         trap - EXIT INT HUP QUIT TERM
         exit "$code"
     }
     trap cleanup EXIT INT HUP QUIT TERM
 
     file=$(mktemp --tmpdir pomfXXXXXXXX.png)
+    errorfile=$(mktemp --tmpdir pomfXXXXXXXX.log)
 
     log() {
         local level
@@ -55,7 +58,7 @@ if flock -n 4; then
 
     optipng "$file"
 
-    url=$(pomfload "$file") || die warning "Failed to upload screenshot"
+    url=$(pomfload "$file" 2>$errorfile) || die warning "Failed to upload screenshot.$(echo;cat "$errorfile")"
 
     echo "$url"
 
diff --git a/pomfload b/pomfload
--- a/pomfload
+++ b/pomfload
@@ -6,24 +6,40 @@ if [ "$#" -lt 1 ]; then
     exit 1
 fi
 
+newline='
+'
+
 result=0
 for f do
     if ! pomf_reply="$(curl -sS --progress-bar -F "files[]=@$f" http://pomf.se/upload.php)"; then
         echo "Failed to upload $f" >&2
         result=1
     else
-        if ! pomf_id=$(printf %s\\n "$pomf_reply" | jq -r '.files[0].url'); then
+        if ! pomf_reply_parsed=$(printf %s\\n "$pomf_reply" | jq -r '.success, .error, .files[0].url'); then
             echo "Failed to parse uploader response to $f" >&2
             printf "Response:\n%s\n" "$pomf_reply" >&2
             result=1
+            continue
+        fi
+
+        pomf_success=${pomf_reply_parsed%%"$newline"*}; pomf_reply_parsed=${pomf_reply_parsed#*"$newline"}
+        pomf_error_message=${pomf_reply_parsed%%"$newline"*}; pomf_reply_parsed=${pomf_reply_parsed#*"$newline"}
+        pomf_id=$pomf_reply_parsed
+
+        if [ "$pomf_success" != true ]; then
+            echo "Failed to upload $f" >&2
+            echo "Server error: $pomf_error_message" >&2
+            result=1
+            continue
         fi
 
         if [ "$#" -gt 1 ]; then
             printf "%s: " "$f"
         fi
 
-        echo "http://a.pomf.se/$pomf_id"
-        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "http://a.pomf.se/$pomf_id" "$f" >> ~/.pomf_history
+        url=http://a.pomf.se/$pomf_id
+        echo "$url"
+        printf '%s\t%s\t%s\n' "$(date --rfc-3339=seconds)" "$url" "$f" >> ~/.pomf_history
     fi
 done
 exit "$result"
